- src/core/mage_hts_engine_impl.cpp
Appears to be a typo: break should be used to exit from the loop only, in order to allow the proper function wrap-up
> Exiting from loop instead of return

- src/android/RHVoice-core/src/main/jni/native.cpp
- src/audio/SConscript
- src/audio/audio.cpp
- src/audio/playback_stream.cpp
- src/core/document.cpp
- src/core/emoji.cpp
- src/core/userdict.cpp
- src/include/audio.hpp
- src/include/core/brazilian_portuguese.hpp
- src/include/core/document.hpp
- src/include/core/dtree.hpp
- src/include/core/emoji.hpp
- src/include/core/ini_parser.hpp
- src/include/core/language.hpp
- src/include/core/mage_hts_engine_impl.hpp
- src/include/core/rules.hpp
- src/include/core/russian.hpp
- src/include/core/std_hts_engine_impl.hpp
- src/include/core/trie.hpp
- src/include/core/userdict.hpp
- src/lib/lib.cpp
- src/sd_module/speech_synthesizer.cpp
- src/service/service.cpp
- src/test/test.cpp
- src/utils/make-hts-labels.cpp
- src/utils/transcribe-sentences.cpp
std::auto_ptr is a very old construct with known issues. This patch gets rid of it.
> Replacing auto_ptr with shared_ptr, fixing several invalid usecases

- src/audio/portaudio.cpp
- src/include/audio.hpp
- src/test/test.cpp
Unbreaking false-failures in PortAudio backend:
* Allowing paOutputUnderflowed return status from Pa_WriteStream(), which is actually not an error. This is a highly important fix, which resolves random interruptions of synthesis in the middle of the phrase with the RHVoice-test.
* Adding a proper non-zero value for Pa_OpenStream() framesPerBuffer argument, and its propagation by RHVoice-test as a buffer_size parameter.
> Fixing interruptions of PortAudio-based voice synthesis due to false-failures

- README.md
“License” word was written in lowercase whilst the real file name in uppercase (except its extension).
> Fix broken link to LICENSE.md in the README.md

- src/include/core/sample_rate.hpp
that has been leaked from the experimenting into the PR.
The bug has been introduced in https://github.com/Olga-Yakovleva/RHVoice/pull/135/files#diff-77cffe8341bf99e3beb9f65df6f5eb8bR45 and hasn't affected speech_dispatcher and RHVoice-test, that's why gone undetected into `master`.
Fixes: #180
> Reverting the default sample rate setting from 48k back to 24k

- src/CMakeLists.txt
in 7a93bccbf530d5072e3cfc98b459ae9104987ce3
> Fixed CMake build broken because of moving config.h.in for includes into another dir

- cmake/Hardening.cmake
- cmake/clangLinkerWorkaround.sh
It turned out that position-independent code was not enabled, and enabling it breaks build with clang because of a long-ignored bug in clang (clang uses wrong shared libs). Implemented a workaround to it (works only for nixes now, for windows we need to reimplement the same script in WSH JS).
> Fixed hardening script.

- src/sapi/IEnumSpObjectTokensImpl.cpp
- src/sapi/IEnumSpObjectTokensImpl.hpp
- src/sapi/ISpDataKeyImpl.hpp
- src/sapi/SpeakImpl.hpp
- src/sapi/dbg_out.hpp
- src/sapi/registry.hpp
- src/sapi/text_iterator.hpp
- src/sapi/tts_base.cpp
- src/sapi/utils.hpp
- src/sapi/voice_attributes.hpp
- src/sapi/voice_token.hpp
This makes it a bit easier to read.
> Added an empty line between different kinds of includes in the SAPI5 module

- CMakeLists.txt
- src/test/CMakeLists.txt
- src/test/test.cpp
- src/utils/CMakeLists.txt
- src/utils/make-hts-labels.cpp
When debugging memory safety issues I found that both MSan and valgrind point to tclap. I have tried CLI11 (with zero success, now they point to CLI11). Anyway, being able to switch between different libs is useful because any of them can acquire a grave bug and we should be sure that the bug is not in the lib but in our code.
> Allowed to use CLI11 instead of tclap for CLI.

- data/CMakeLists.txt
There was a new voice released with #234, but it wasn't added to correspondig cmake file, so now it leads to build failure.
This PR fixes it.
> Fix Arina's voice lang definition in cmake

- CMakeLists.txt
this PR make documentation dir (currently it is used as base path for voices license files) configureable.
it will help some distros to configure buildsystem to install package files to proper paths.
For example, on gentoo, package **MUST** install it's doc files to `/usr/share/doc/PkgName-PkgVersion[-revision]`, and currently RHVoice installs (without patching) licenses to `/usr/share/doc/$voicename/copyright`.
It is anyway will be better to keep voices docs ad licenses under at least `/usr/share/doc/RHVoice`, and not under "raw" `/usr/share/doc/`, but at least making it configureable untie hands for many distro maintainers.
> make doc path configureable

- CMakeLists.txt
[This commit](https://github.com/Olga-Yakovleva/RHVoice/commit/90aeda8ed27bc26560256aeb1d30912380de3f74) introduced "IPO" checks. But looks like author forgot that CMake requires policy rule for `CMP0069` to be set if `check_ipo_supported()` function is used (see [Cmake documentation on that policy and related links](https://cmake.org/cmake/help/v3.18/policy/CMP0069.html)).
Without this fix in `cmake/Hardening` - compilation fails.
Without this fix in other places - CMake throws a billion of warnings about that (and disables hardening on all the subprojects)
This PR fixes all of that.
> cmake hardening fix

- src/sd_module/CMakeLists.txt
`CMAKE_INSTALL_LIBDIR` is preferred over `CMAKE_INSTALL_PREFIX/lib`, since it can be "lib64", "lib32" or even "libx32" (until latter isn't deleted from linux kernel and other OSes where it (was) supported.
> Fix SD module install path in cmake

- src/CMakeLists.txt
It makes it possible to disable some parts of package, which can be useful in various cases:
Say, user1 wants to install "service-only" on "server" (or PC), and "client-only" on a laptop (or smartphone), and don't need sd module.
Or, maybe user2 only needs sd-module, but doesn't want neither utils, service, nor client.
And even tests.
> more configurability

- src/service/CMakeLists.txt
currently (with `BINDIR` variable, which, looks like be not anywhere), installed service file have exec path `/RHVoice-service` (in root dir), which is not the place where it is installed.
This PR fixes `@bindir@` placeholder substitution for proper `RHVoice-service` install path.
> fix bindir substitution in service file

- src/nvda-synthDriver/__init__.py
UnicodeEncodeError on unknown characters
A virtual buffer in Firefox browse documend mode crash and it was impossible to continue scrolling with the arrow this fixes #235
> fixed Olga-Yakovleva/RHVoice/#235

- .github/workflows/codeql-analysis.yml
implemented CodeQL via github actions.
~~c++ scanning on windows currently not works. i think another scons weirdness.~~
will merge without windows C++ scanning. most of our code base are cross
platform anyway. 😉
look at all this green checks! ✔
> enable CodeQL

- src/third-party/hts_engine/CMakeLists.txt
Ran into an issue with relinking math functions on `hts_engine`. So suggesting small fix for it.
> Fix hts_engine relink issue

- site_scons/RHVoicePackaging/nvda.py
- src/nvda-synthDriver/__init__.py
NVDA-synthDriver: Fixed RHVoice to work with NVDA >= 2021.1
Import speech commands from speech.commands when possible, otherwise import commands from speech itself for backwards compatibility with NVDA versions below 2019.3
Fixes #272
> Update RHVoice NVDA-synthDriver to work with NVDA versions >+ 2021.1

- .gitmodules
this really reduces the time it takes to clone the repository, besides
in this case, we do not need the complete history of the cldr repository.
> make cldr a shallow clone

- README.md
"##android" in URL did not worked, because markdown is not supported ID.
And others small fixes.
> cosmetic fixes

- .gitmodules
it turned out that if we track the tag, then the repository is cloned with a depth of 1 and then, when searching for a ref, it is cloned completely.
Reverts RHVoice/RHVoice#317
> Revert "make cldr a shallow clone"

- SConstruct
- src/core/SConscript
Also update the shared library version.
The rest of the updates before the release shouldn't touch the core itself, unless something important really needs fixing.
> Core: set the version number to the next release version

- data/SConscript
The version string now includes the language version encoded as a single number. So if we update the language and rebuild the voice package, a different package version string will be generated automatically.
> Change the format of the voice addon and exe package version strings

- SConstruct
- data/SConscript
- src/include/core/macedonian.hpp
This is an important emergency fix. Moving to 1.4.1 for compatibility reasons.
> Core: fix the Macedonian language identifier value

- src/core/CMakeLists.txt
- src/third-party/sonic/CMakeLists.txt
Fixed an error in CMake script adding sonic depending on ENABLE_MAGE
Made pkg-config sonic non-mandatory.
Added a message for the case sonic is not found in pkg-config and is built by us.
> Fixes in CMake scripts related to libsonic.

- src/CMakeLists.txt
- src/bin/CMakeLists.txt
- src/sd_module/CMakeLists.txt
Instead they are now built depending solely on the BUILD_ options, but these options are initialized depending on the presence of components' dependencies. So a user can override these options, if he really needs so (it would fail, if the dependencies are not met, but he can provide them too via the cache vars set by pkg-config).
> Disconnected conditional building of speech_dispatcher module and DBus servers and clients from platform.

- SConstruct
this helps rhvoice build reproducibility.
> honor 'SOURCE_DATE_EPOCH' environment variable if it's set.

- src/nvda-synthDriver/__init__.py
RHVoice is no longer available in the NVDA synthesizer selection dialog if there are no voices installed
SynthDriver.check method returns True only if at least one voice addon is running
this fixes #267
> Fix NVDA driver availability without installed voices

- src/scripts/general/voice-building-utils
- src/scripts/hts/data/Makefile.in
- src/scripts/hts/data/scripts/convert-audio
- Convert-audio converted to py3.
- voice-building-utils: fixed no key guess_f0_method.
- makefile.in calls convert-audio with python3, not python2.
> voice-building-utils correction and convert-audio to py3 migration.

- src/scripts/hts/scripts/Config.pm.in
- src/scripts/hts/scripts/Training.pl
* Only each parameter type is clustered independently in this version, not each state, so it will only be able to take advantage of up to 4 cores.
* The Parallel::ForkManager Perl module is now required to run the training script.
* Change the value of the $NUMPROC variable in scripts/Config.pm to let the script run the clustering steps in parallel. See above, no sense in setting it to a value grater than 4.
* Remember that it will mean more memory usage, so be careful. If the training crashes, it's very likely your server ran out of memory executing those steps at the same time.
> Partially parallel context clustering.

- src/scripts/hts/scripts/Config.pm.in
- src/scripts/hts/scripts/Training.pl
The default behaviour remains the same: 2 iterations as in the original HTS demo scripts.
If you increase the value of $NUMCL in scripts/Config.pm, more iterations of untying the parameters, reestimation and clustering will be performed.
> Voice training: support additional iterations of tree context clustering.

- src/core/document.cpp
- src/core/language.cpp
- src/include/core/document.hpp
- src/include/core/item.hpp
- src/include/core/language.hpp
- src/include/core/ssml.hpp
- src/include/core/tts_markup.hpp
- src/include/core/xml.hpp
One phoneme element is considered a single word. Use multiple elements if you need to transcribe multiple words in a row.
> SSML: support the phoneme element, only native phonemes are supported.

- src/nvda-addon/synthDriver/__init__.py
Closes #485
Moved the rate boost setting to the conventional position (both in the settings dialog and the settings ring), so it's now right after the rate slider.
> Move Rate Boost setting to the conventional position.

- src/sd_module/CMakeLists.txt
Use pkgconfig to get the location to install speech-dispatcher modules, since speech-dispatcher-0.11 changed from installing them in `{libdir}/speech-dispatcher-modules` to `{libexec}/speech-dispatcher-modules`.
I do not have much experience with CMake, so it is possible that my approach is not optimal, but I tested building against speech-dispatcher-0.9.1 (which does not expose a `modulebindir` pkg-config variable) and speech-dispatcher-0.11.1 (which does) and the sd_rhvoice module was installed in the correct location in each case.
(Obsoletes #503.)
> Support new speech-dispatcher modules location

- config/dicts/english/example.txt
In the past, we had only russian description of the dictionaries, and which types of rules do we have to make the dictionary articles for altering the RHVoice pronounciation.
Now, we have the russian rules, with the descriptions written in english for each rule. 
Russian rules were chosen, because these rules are well known and documented.
> Short english comments for the dictionaries example

- src/scripts/general/voice-building-utils
This update fixes the situation, where the lpc making is not working on newer python 3.10 and newer systems, like ubuntu 22.04.01 Lts, i.e, anything which uses newer python, scipy and numpy.
I also took care of the backwards compatibility. Tested this on python 3.8 (OLD ONE) and 3.10 (NEW ONE).
> Voice building utils: fixed lpf making with latest scipy and python 3.10 on latest linux systems

- src/scripts/general/import.praat
From now on, when training voices, new praat can be used, along with the old one.
We can use praat from 6.0.xx to 6.3.
> Voice building utils: changes for new praat

- site_scons/RHVoicePackaging/nvda.py
Updated the compatibility information for the new NVDA version, as the beta 1 from NV acess is declared. We are doing this to ensure compatibility with the new future NVDA version.
> Compatibility with future NVDA stable version

- src/scripts/general/voice-building-utils
Ids are useful for associating sentences in text with corresponding audio files. When importing, only the files mentioned in the ssml will be copied, and not finding a file will cause an error.
> Import-recordings: handle file names in xml:id.

- src/core/hts_engine_impl.cpp
- src/include/core/hts_engine_impl.hpp
If the developer wants the voice to have slightly higher or lower pitch by default. The value is in semitones.
> Pitch_shift property in voice.params.

- src/core/document.cpp
- src/core/engine.cpp
- src/core/language.cpp
- src/include/core/document.hpp
- src/include/core/engine.hpp
- src/include/core/language.hpp
- src/include/core/utterance.hpp
This is meant for the case of a second language sharing most of the alphabet with the first language. The first language is the default. The second language is chosen only if a matching word is found with no clashes with the first language. The phoneme mapping is used the same way as for pseudo-English.
> Another kind of simple language switching.

- src/scripts/hts/scripts/Config.pm.in
- src/scripts/hts/scripts/Training.pl
In the default setup we had partly initialized the phonemes.
Let's do this fully from now on.
In the training.pl, lines 353, and 354, there is an -i parameter, with the variable. The variable has the reference in the config.pm.
From the config.pm, the initialization reestimation can be fine tuned.
$NUMPHON option accepts values from 20 to 100.
> Initialization reestimation improvement: let's use more iterations to load our models fully

- src/nvda-addon/synthDriver/__init__.py
Debugged with the help of:
@Olga-Yakovleva
> Fixed not working speech commands in NVDA 2019.3 and later

- src/android/RHVoice-core/src/main/res/values-es/strings.xml
Fix up #836 
I license this contribution under the terms set out in the Unlicense license.
> Added manually-translated Spanish strings for the Android app.

- site_scons/RHVoicePackaging/nvda.py
- src/nvda-addon/globalPlugin/RHVoice_globalPlugin.py
- src/nvda-addon/installTasks.py
- src/nvda-addon/synthDriver/__init__.py
A massive refactoring of NVDA driver.
Minimum compatible NVDA version as of this PR is NVDA 2021.1.0
Dropped python 2 support, what means of dropping support windows versions earlier than Windows 7 Service pack 1.
No need to support older NVDA versionns than 2021.X because users can easily upgrade their installations.\Removed converters to ssml and replaced them with NVDA's builtin converter.
It should not make any difference for users, but testing is needed anyway.
> Refactor nvda driver

- src/scripts/general/voice-building-utils
* added new pitch extractor, rmvpe:
The version working with cpu can be found in my fork of this extractor. This extractor has proven itself to woork on the low pitched voices, too. 
Options for configuring the location of this extractor are added, too (training.cfg should be edited.) Examples below:
"rmvpe_dir": "/home/asael/tts/RMVPE",
"rmvpe_model_path": "/home/asael/tts/RMVPE/model.pt",
Soon I am going to write the conprehensive setup guide in the RHVoice wiki. 
The modified fork of this extractor can be found on the following link: 
https://github.com/zstanecic/RMVPE
The model for rmvpe can be found here:
https://github.com/yxlllc/RMVPE/releases/download/230917/rmvpe.zip
* Added an option to the configuration file for turnin off the audio normalization provided by RHVoice before the …
> Voice building utils: fixes and additions

- site_scons/RHVoicePackaging/nvda.py
- src/nvda-addon/synthDriver/__init__.py
In the future NVDA 2025.1, audio devices in the NVDA user configuration will be stored as endpoint Ids instead of friendly names.
Changed the audio device lookup and selection strategy. We are trying two approaches: one from the old stable NVDA, and one which will be introduced in 2025.1
So, in the synth driver, we are using the following statements:
try:
player = nvwave.WavePlayer(channels=1, samplesPerSec=self.__sample_rate, bitsPerSample=16, outputDevice=config.conf["speech"]["outputDevice"])
except:
player = nvwave.WavePlayer(channels=1, samplesPerSec=self.__sample_rate, bitsPerSample=16, outputDevice=config.conf["audio"]["outputDevice"])
So, from now on, the new key for the ouptput device is not located in speech, but in audio, and I am maintaining the backwards compatibility, as …
> NVDA driver compatibility with NVDA 2025.1 and older

- src/core/emoji_data.cpp
This makes available the cldr version 46 for all languages supported. Languages which need this will be updated in a subsequent pull request.
> CLDR emoji code update for the cldr version 46

- src/nvda-addon/SConscript
* removed the hardcoded russian manifest, it was the source of the failing add-on datastore checks.
* NVDA addon version is splitted from the RHVoice core version.
> NVDA addon: NVDA addon version is splitted from the core
