src/service/SConscript
=> Fix build script, replace tab with spaces

src/android/.gitignore, src/android/RHVoice-core/build.gradle, src/android/RHVoice-core/gradle.properties, src/android/build.gradle, src/android/gradle/wrapper/gradle-wrapper.properties
Updated android gradle plugin to 3.6.0.
added a new myNdkVersion variable to set specific ndk version (Needed by new android plugin).
updated dependencies to latest versions
updated compile and target sdk versions to 29 (android 10) & buildTools to 29.0.3
added gradle.properties to set variables for androidx support (Needed by newer android plugin versions)
updated .gitignore
=> Android build system update

SConstruct
'targetcross' is used for cross-compilation.
fixes #20
=> Add 'targetcross' CSons variable

SConstruct, src/third-party/rapidxml/rapidxml/rapidxml_iterators.hpp
=> Updating RapidXML in order to fix issues seen in Clang 11

SConstruct
Reverts Olga-Yakovleva/RHVoice#122
something bad happened with scons will re visit later.
=> Revert "Add 'targetcross' CSons variable"

SConstruct, data/SConscript, src/core/SConscript
=> Scons fixes

config/RHVoice.conf
also add a link to configuration documentation.
=> translate the configuration file into English

config/RHVoice.conf
Fixed grammar and spelling issues in the english configuration file
@alex19EP
=> Configuration file fixes

LICENSE.md, data/voices/artemiy/Readme-en.txt, data/voices/artemiy/Readme-ru.txt, doc/en/Binaries.md, doc/ru/Binaries.md
I fixed links for Artemiy, and edit license.md.
=> Fix Artemiy links

.gitmodules, CMakeLists.txt, src/audio/CMakeLists.txt, src/bin/CMakeLists.txt, src/core/CMakeLists.txt, src/lib/CMakeLists.txt, src/sd_module/CMakeLists.txt, src/service/CMakeLists.txt, src/test/CMakeLists.txt, src/third-party/hts_engine/CMakeLists.txt, src/third-party/mage/CMakeLists.txt, src/third-party/sonic/CMakeLists.txt, src/utils/CMakeLists.txt
Just adds options to build with sanitizers enabled.
=> Added sanitizers support

SConstruct
not everyone uses scoop and likes environment variables. this fixes #231
=> widen scons checks

SConstruct
See discussion at this commit
https://github.com/RHVoice/RHVoice/commit/92c9eecb7def68c82f979eaf2f85d3d54879df07
=> Show message when Georgian is skipped during build

SConstruct
it should have been done earlier ... but oh well.
=> bump version to 1.2.4

doc/en/Binaries.md
* corrected misspelled brazilian voice name on the binaries english page. 
* consulted with @beqabeqa473
=> Fixed typo on the binaries downloads page

README.md
This pull request fixes the Letícia voice name in the readme file itself, so that it shows up properly.
=> Accent mark fix: letícia voice 

site_scons/RHVoicePackaging/common.py, site_scons/RHVoicePackaging/nvda.py, site_scons/RHVoicePackaging/windows.py, src/sapi/tts_base.cpp
- Windows packages: stop using my name everywhere
- SAPI5: extend the list of places where we are looking for language and voice data files with our new location.
=> win pkg dev name

src/android/RHVoice-core/src/main/java/com/github/olga_yakovleva/rhvoice/android/DataPack.java, src/android/RHVoice-core/src/main/java/com/github/olga_yakovleva/rhvoice/android/VoiceListAdapter.java, src/android/RHVoice-core/src/main/java/com/github/olga_yakovleva/rhvoice/android/VoiceViewHolder.java, src/android/RHVoice-core/src/main/res/layout/voice_list_item.xml
A brief attribution statement should be placed in attrib.html file in the voice zip package.
This is probably a temporary solution because of my lack of time to think it through properly.
=> Android: support displaying the attribution information for a voice

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, src/android/build.gradle, src/android/gradle/wrapper/gradle-wrapper.properties
update gradle to 7.2
update AGP to 7.0.0
=> chore: update gradle and AGP

.github/workflows/codeql-analysis.yml
=> fix codeql action

doc/en/index.md, doc/ru/index.md, doc/ua/index.md
Update language links in index.md files.
=> Doc: update language links

doc/en/Binaries.md, doc/ru/Binaries.md, doc/ua/Binaries.md
=> doc: update binaries.md

src/audio/audio.cpp, src/core/emoji.cpp, src/core/phoneme_set.cpp, src/include/core/hts_input.hpp, src/include/core/resource.hpp, src/include/core/str.hpp, src/include/core/userdict.hpp, src/include/core/voice_profile.hpp, src/include/core/xml.hpp, src/lib/lib.cpp
@Olga-Yakovleva @maniyax @alex19EP ,
Minor correction and rewriting of code parts to more secure and correct according to the C++ standard, some minor code optimizations.
=> Code refactor and minor optimization

doc/en/Compiling-on-Linux.md, doc/ru/Compiling-on-Linux.md
Hello. I recently ran into [this](https://github.com/RHVoice/RHVoice/issues/428#issuecomment-1002266719) problem. I suggest updating the assembly instructions to avoid problems in the future.
=> #428 update linux build instruction

doc/en/Compiling-on-Linux.md, doc/ru/Compiling-on-Linux.md
I updated the [dependencies](https://github.com/RHVoice/RHVoice/issues/382) in the document, as the ones listed there are not enough to successfully build the project.
=> update dependency's in linux build documents

src/scripts/general/voice-building-utils, src/scripts/hts/Makefile.in
Fixes #187.
- voice-building-utils runs on Python3.
- For guess-f0-range, method configured in guess_f0_method of training.cfg is used. If not set, sptk_rapt is used as earlier.
- makefile properly calls perl with ./scripts/Training.pl and ./scripts/Config.pm
=> Voice-building-utils update.

src/scripts/general/voice-building-utils
- Voice-building-utils: use numpy to convert input and output in pitch extraction with sptk.
- Voice-building-utils: a new extract-mgc command.
=> mgc with world

src/scripts/general/voice-building-utils, src/scripts/hts/data/reftrees/dur.inf, src/scripts/hts/scripts/Training.pl
- Voice-building-utils: a way to combine two pitch extractors with the first one being the prefered.
- Training.pl: support for reference trees.
- A reference tree for duration.
=> Training scripts updates

src/android/RHVoice-core/src/main/res/values-fi/strings.xml, src/core/document.cpp, src/core/language.cpp, src/include/core/document.hpp, src/include/core/language.hpp, src/include/core/str.hpp, src/scripts/general/att2bin
Allows tok.foma to see the contents of a whole sentence. Tutorial will follow.
=> Core: sentence level tokenization support.

src/android/RHVoice-core/build.gradle, src/android/RHVoice-core/src/main/AndroidManifest.xml, src/android/RHVoice-core/src/main/res/xml/netsec.xml, src/android/RHVoice-data/build.gradle, src/android/build.gradle
- Android: increment version number.
- Android: upgrade dependencies.
- Android: upgrade the Gradle plugin.
- Android: remove debug signing config.
- Android: android:exported attribute for Android 12 compatibility.
- Android: remove the obsolete network security config.
- Android: target Android 12.
=> Android updates

src/scripts/general/text2ssml.py
Added Python script for converting text files into SSML format, required by voice building tools.
=> Add script to convert text files to SSML format

src/scripts/Polish/checktrans-cases.ssml, src/scripts/Polish/checktrans-expected-results.txt, src/scripts/Polish/g2p.foma
Further pronounciation improvements.
=> Polish rev. 10.

src/android/RHVoice-core/build.gradle, src/android/RHVoice-core/src/main/java/com/github/olga_yakovleva/rhvoice/TTSEngine.java
This may not be the reason though. But trying things I can think of.
=> Android: trying to prevent System.loadLibrary crashes on 5.1 and earlier.

fastlane/metadata/android/eo/full_description.txt, fastlane/metadata/android/pl/full_description.txt, fastlane/metadata/android/pl/short_description.txt, fastlane/metadata/android/pl/title.txt, src/android/RHVoice-core/src/main/res/values-pl/strings.xml
I license this contribution under the terms set out in the 0BSD license.
=> translations of F-Droid descriptions (Esperanto + Polish)

data/languages/Albanian/emoji.fst, data/languages/Albanian/language.info, src/scripts/general/import-emoji
* albanian: updated emoji files and bumped language to 1.20
* updated cldr to the minor released revision, that is v 41.
* Updated emoji generation script to be able to generate polish and albanian language support for emoji.
=> Import-emoji: update languages, for which we have to generate emoji support fst's

src/audio/audio.cpp, src/core/emoji.cpp, src/core/phoneme_set.cpp, src/include/core/hts_input.hpp, src/include/core/resource.hpp, src/include/core/str.hpp, src/include/core/userdict.hpp, src/include/core/voice_profile.hpp, src/include/core/xml.hpp, src/lib/lib.cpp
- Revert #405 because of licensing issues
- Use swap to replace one of the improvements of #405.
=> revert 405

src/audio/audio.cpp, src/core/emoji.cpp, src/core/phoneme_set.cpp, src/include/core/hts_input.hpp, src/include/core/resource.hpp, src/include/core/str.hpp, src/include/core/userdict.hpp, src/include/core/voice_profile.hpp, src/include/core/xml.hpp, src/lib/lib.cpp
- Revert "Use swap to replace one of the improvements of #405."
- Revert "Revert #405 because of licensing issues"
=> Restore #405

.gitmodules
Next generation of Vitaliy voice based on the new World vocoder, which gives high quality, without affecting responsiveness.
Only one voice will remain in repository later.
=> voices: add Vitaliy-ng

.gitmodules, data/CMakeLists.txt
=> voices: add Timofey voice

.gitmodules, data/CMakeLists.txt
language - polish,
license: cc-, creative commons cc zero, public domain.
All credits and further information are in the readme. Packages will be generated soon.
=> voices: add Michal

src/android/RHVoice-core/src/main/res/values-ca/strings.xml
I license this contribution under the terms set out in the MIT-0 license.
=> Add Catalan strings.xml

src/scripts/Polish/chardesc.tsv, src/scripts/Polish/unicodechars.foma
Note: this is not yet going to be packaged, as there will be addition to this in form of emoji data, respectively.
This should be merged first before my proceeding.
=> Polish update to revision 13

src/scripts/general/voice-building-utils
При извлечении MGC, теперь используется  параметр f0_floor. При таком подходе, рассчитывается правильный fft в зависимости от нижней границы и частоты дискретизации. Таким образом, пропадают искажения, особенно на низких голосах. Добавлены новые методы извлечения F0: "world_dio" и "world_harvest" - прописываются в training.cfg. При использовании алгоритма Harvest для извлечения F0, улучшает картину F0, что ведёт за собой менее фрагментарный звук на оттренированном голосе. Так же в документации World написано, что Harvest лучше извлекает f0 для низких голосов. На тестах проверено, действительно, Harvest показывает лучшие результаты на ресинтезе в world. Алгоритм harvest затратен по времени, приблизительно одну треть  времени общего объёма аудиоданных.
When extracting MGC, the parameter …
=> Voice building utils - improvements to mgc extraction, and two new f0 guessers / extractors

.gitmodules, data/CMakeLists.txt
This voice was trained on the full polish dataset, which we use for the polish language voices, respectively. This voice was trained using world. Packages will be published soon./
=> Cezary - new polish male voice

src/scripts/general/voice-building-utils
Coauthored by: Sergey parshakov
=> voice building- maintenance update

src/scripts/Polish/checktrans-cases.ssml, src/scripts/Polish/checktrans-expected-results.txt
This mainly addresses users feedback regarding word pronunciation. New msi will be available soon.
=> Polish rev. 14

src/scripts/Polish/pg2p.foma, src/scripts/Polish/tok.foma
what's new
Fixed reading of the w and z prepositions, when surrounded by other symbols,
fixed spelling on android, and other programs which don't support spelling corrections, applies to these prepositions abowe,
Corrected the polish voices metadata, applies to Cezary,
Added the voicing parameter, for v 1.12, to improve the voice sounding: applies to michal, natan and cezary.
Coauthored by: grzegorz Złotowicz, a.k.a grzezlo
=> Polish related changes

.gitmodules, data/CMakeLists.txt, site_scons/RHVoicePackaging/windows.py, src/android/RHVoice-core/src/main/res/values-cs/strings.xml, src/scripts/Czech/checktrans, src/scripts/Czech/checktrans-cases.ssml, src/scripts/Czech/checktrans-expected-results.txt, src/scripts/Czech/downcase.foma, src/scripts/Czech/dur-mod.tree, src/scripts/Czech/foma2fst, src/scripts/Czech/g2p.foma, src/scripts/Czech/gpos.foma, src/scripts/Czech/key.foma, src/scripts/Czech/lseq.foma, src/scripts/Czech/msg.foma, src/scripts/Czech/numbers.foma, src/scripts/Czech/pg2p.foma, src/scripts/Czech/phrasing.tree, src/scripts/Czech/pitch-mod.tree, src/scripts/Czech/spell.foma, src/scripts/Czech/stress.foma, src/scripts/Czech/syl.foma, src/scripts/Czech/tok.foma
co-authored by darko milosevic, @darko.milosevic86
=> Czech - cs / cz

src/scripts/general/setup_environment_debian
new file:   src/scripts/general/setup_environment_debian
This script sets up the environment for building a new RHVoice voices, and automatically regenerates RHVoice/src/scripts/general/training.cfg with the bindir, htk341_bindir, hts22_bindir, and festdir paths.
=> Added bash script for setting up environment for building a new voices

doc/en/Compiling-for-Android.md, doc/en/Configuration-file.md, src/android/gradle.properties
new file:   doc/en/Compiling-for-Android.md
modified:   doc/en/Configuration-file.md
modified:   src/android/gradle.properties
Added gradle paralell builds. See link for more info:
https://docs.gradle.org/current/userguide/performance.html#parallel_execution
=> Gradle Paralell Builds & Docs improvements

site_scons/RHVoicePackaging/windows.py, src/android/RHVoice-core/src/main/res/values-sr/strings.xml
added serbian localization for android, coauthored with @DarkoMilosevic86 
added uzbek and serbian localizations for nsis installers, respectively.
=> Nsis and android: localization additions

SConstruct, src/android/RHVoice-core/build.gradle, src/core/SConscript, src/core/data_only_language.cpp, src/core/document.cpp, src/core/english_id.cpp, src/core/hts_labeller.cpp, src/core/language.cpp, src/core/userdict.cpp, src/include/core/data_only_language.hpp, src/include/core/document.hpp, src/include/core/english_id.hpp, src/include/core/language.hpp, src/include/core/voice_profile.hpp
Core updates for 1.14.0 release. These changes were needed for some languages soon to be published.
=> Core updates

doc/en/Packaging-status.md, doc/ru/Packaging-status.md, doc/ua/Packaging-status.md
The following changes have been made to the Packaging-status.md file for all three languages:
* Ukrainian documentation is synchronized with English and Russian.
* Distributions are listed in alphabetical order.
* Added warning about lagging versions in distribution repositories.
* Added information about the following distributions: ALT Linux, Debian, Fedora, Manjaro, and RED OS.
* Other minor edits.
=> Update Packaging status in documentation

src/scripts/general/setup_environment_debian
Fixed issue with the chmod +x praat command
=> Changed Praat version to the latest version praat6317_linux64barren

src/scripts/general/voice-building-utils
We install:
``pip install penn``
``and just use the script as usual.``
This pull request implements the f0 extractor from the following paper:
M. Morrison, C. Hsieh, N. Pruyne, and B. Pardo, "Cross-domain Neural Pitch and Periodicity Estimation," Submitted to IEEE Transactions on Audio, Speech, and Language Processing, <TODO - month> 2023.
Tested by: @zstanecic 
co-authored by: Sergey parshakov
=> voice building utils: pitch extraction with the new f0 extractor - penn 

doc/en/Packaging-status.md, doc/ru/Packaging-status.md
=> Packaging-status.md: add Gentoo packages

site_scons/RHVoicePackaging/windows.py
* this will be needed for the future pull request.
=> Enable Nsis croatian translation

.gitmodules, data/CMakeLists.txt, src/scripts/general/import-emoji
Added croatian language with croatian voice
Emoji script also supports croatian
=> Croatian - hr

.gitmodules, data/CMakeLists.txt
Seva - new russian voice created by the RHVoice lab team and extensively tested.
=> Seva - Rus

src/scripts/Czech/lseq.foma, src/scripts/Czech/spell.foma, src/scripts/Czech/tok.foma
* fixed the bug, where camel case tokenizer failed on the ď and Ď characters, especially when these were part of words.
* small additions to dictionary, last minute ones,
* small refinements to spelling and lseq
=> New quick fix for czech

src/scripts/Czech/lseq.foma, src/scripts/Czech/spell.foma, src/scripts/Czech/tok.foma
This update is based on community suggestions:
* [SAPM](https://www.tumblr.com/rhvoice-ec/774835280946528256/our-spanish-implementations-using-sentence-based) was improved.
* More cases for handling of acronyms (AKA "siglas" in Spanish)
* Two new stylized alphabets.
* Pitch for wh questions.
* Minor pronunciation improvements.
* Updated voice with better sounding.
=> Updates for Spanish

doc/en/Packaging-status.md, doc/ru/Packaging-status.md, doc/ua/Packaging-status.md
Good time of day. We have updated and repackaged the RHVoice package. What we are making changes to the documentation about.
=> update packaging doc

src/android/RHVoice-core/src/main/res/values-hu/strings.xml
This was translated by the native hungarian speaker. This will be needed for the future hungarian language builds when they appear.
authored by: Till Nikolett, tillnikolett@gmail.com
Published by: Zvonimir stanecic, zvonimirek222@yandex.com
=> Hungarian translation for the android app

src/scripts/general/requirements.txt, src/scripts/general/setup_environment_debian, src/scripts/general/voice-building-utils
* A progress bar has been added while processing acostic features.
* Added --skip to some tasks to process, for example, a dataset in which new wavs/text have been added and you want to process only those new data instead to process all from scratch again.
* Lf0, bap and mgc can now be processed using multiple cores for speedup. use the argument called `--cores` preceded by a number for it. Example: --cores 1 will process in the original behavior, --cores 4 will use 4 CPU cores.
* Added requirements.txt to run this tool properly.
* Run `pip install -r path/to/general/scripts/requirements.txt` to make sure you have all dependencies, including new ones.
supersedes #867
=> voice-building-utils: several improvements
